POST http://localhost:4001/api/user/signup
Content-Type: application/json

{
    "username": "ibrahim-sh0",
    "email": "ibrahimsh0@example.com",
    "password": "123"
}

###
POST http://localhost:4001/api/user/login
Content-Type: application/json

{
    "username": "ibrahim123",
    "password": "123"
}



###
GET http://localhost:4001/api/product/allProducts
Content-Type: application/json
###

PUT http://localhost:4001/api/product/65e380e52549a5e9892c204e
Content-Type: application/json

{
  "title": "Updated Title",
  "desc": "Updated Description",
  "newprice": 99.99,
  "oldprice": 79.99
}

###
POST http://localhost:4001/api/user/SendMail
Content-Type: application/json

{
    "Email" : "ibrahimkassim975@gmail.com",
    "Subject" : "Hello",
    "Text" :  "Hi there!"
}
